title: Building a Problem Space for Science Translation
description: Team Science and the Translation of Research Findings for Application in the Real World
url: ""
baseurl: "/building-science-translation-problem-space"
theme: minima
markdown: kramdown
plugins:
  - jekyll-seo-tag

header_pages:
  - index.md
  - about.md
  - method.md
  - participate.md
  - contact.md

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
